import pandas as pd

data = pd.DataFrame({
    'text': [
        "I love this product",
        "This is the best thing ever",
        "I hate this",
        "It's terrible",
        "Absolutely amazing",
        "Not great",
        "I don't like it",
        "Very good",
        "Awful experience",
        "Meh",
        "I am so happy with this",
        "This is disappointing",
        "Fantastic work",
        "Poor quality",
        "I feel great about this",
        "Worst purchase ever",
        "Highly recommend it",
        "Do not buy this",
        "Satisfactory performance",
        "Completely useless",
        "Exceeded my expectations",
        "I am thrilled with the results",
        "This is a disaster",
        "Pleasantly surprised",
        "Extremely dissatisfied",
        "Could be better",
        "I'm impressed",
        "Not worth the money",
        "Superb experience",
        "Very bad service",
        "Exceeded all expectations",
        "Very frustrating",
        "Top-notch quality",
        "Will never buy again",
        "Just okay",
        "Love it so much",
        "Disappointing purchase",
        "Highly unsatisfied",
        "Remarkably good",
        "Terribly handled",
        "I am delighted",
        "Waste of time and money",
        "Very happy customer",
        "Extremely poor performance",
        "Good value for money",
        "Never again",
        "Fantastic!",
        "Not impressed",
        "Very satisfied",
        "Regret buying this"
    ],
    'label': [
        'positive', 'positive',
        'negative', 'negative', 'positive',
        'negative', 'negative', 'positive', 'negative', 'neutral',
        'positive', 'negative', 'positive', 'negative', 'positive',
        'negative', 'negative', 'negative', 'neutral', 'negative',
        'positive', 'negative', 'positive', 'negative', 'neutral',
        'positive', 'negative', 'positive', 'negative', 'positive',
        'negative', 'negative', 'neutral', 'positive', 'negative',
        'negative', 'positive', 'negative', 'positive', 'negative',
        'positive', 'negative', 'positive', 'negative', 'positive',
        'negative', 'positive', 'negative', 'positive', 'negative'
    ]
})
